server:
  port:8080
tomcat:
  uri-encoding:UTF-8
spring:
  freemaker:
    allow-request-override:false
    cache:true
    charset:UTF-8
    check-template-location:true
    content-type:text/html
    expose-request-attrbutes:false
    expose-session-attrbutes:false
    suffix:ftl
    template-loader-path:classpath/templates/

  datasource:
    oracle:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      jdbc-url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
      username: hncs
      password: 20190509
      initial-size: 5
      max-idle: 10
      max-wait: 10000
      min-idle: 5

    mssql:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbc-url: jdbc:sqlserver://192.168.2.167:1433;DatabaseName=HIS_HXYW_8.0
      username: sa
      password: qq630717805+

  redis:
    #reids的连接ip
    host: 192.168.2.167
    port: 6379
    password: redis
    #Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    database: 0
    #连接超时时间（毫秒)
    timeout: 10000ms
    #springboot2.0后默认使用lettuce连接redis,底层使用的是netty框架做支撑
    lettuce:
      pool:
        #连接池中的最小空闲连接 默认 0
        min-idle: 0
        #连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        #连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        #连接池中的最大空闲连接 默认 8
        max-idle: 8


logging:
  level:
    org:
      springframework:
        security: DEBUG
    hibernate: DEBUG

  path: concretepage/logs
  pattern:
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'